/**
 * Safari Magic Gallery: gallery logic.
 *
 * Data comes from community_registry.json, generated by scripts/build_registry.py.
 * Every extension is presented equally in one grid; users choose the order with
 * the sort control. Thumbnails are real screenshots (see generate_thumbnails.sh).
 */

// ---------------------------------------------------------------- state
let extensions = [];
let activeCategory = 'all';
let searchQuery = '';
let sortMode = 'newest';

let lastFocusedElement = null;

// ---------------------------------------------------------------- elements
const grid = document.getElementById('extension-grid');
const toastEl = document.getElementById('toast');
const searchInput = document.getElementById('search-input');
const searchClear = document.getElementById('search-clear');
const sortSelect = document.getElementById('sort-select');
const resultCount = document.getElementById('result-count');

const inspectorModal = document.getElementById('inspector-modal');
const closeInspectorBtn = document.getElementById('close-inspector-btn');
const modalTitle = document.getElementById('modal-title');
const modalAuthor = document.getElementById('modal-author');
const modalCategory = document.getElementById('modal-category');
const modalImg = document.getElementById('modal-img');
const modalDescription = document.getElementById('modal-description');
const modalPrompt = document.getElementById('modal-prompt');
const modalCliCmd = document.getElementById('modal-cli-cmd');
const modalOnelinerCmd = document.getElementById('modal-oneliner-cmd');
const copyModalOnelinerBtn = document.getElementById('copy-modal-oneliner-btn');
const modalDownloadPkgBtn = document.getElementById('modal-download-pkg-btn');
const modalDownloadLabel = document.getElementById('modal-download-label');
const modalMetaRow = document.getElementById('modal-meta-row');
const modalSetupLink = document.getElementById('modal-setup-link');
const copyModalPromptBtn = document.getElementById('copy-modal-prompt-btn');
const copyModalCliBtn = document.getElementById('copy-modal-cli-btn');

// Install tab switcher elements
const installTabOneliner = document.getElementById('tab-oneliner');
const installTabCli = document.getElementById('tab-cli');
const installPaneOneliner = document.getElementById('install-pane-oneliner');
const installPaneCli = document.getElementById('install-pane-cli');

const submitModal = document.getElementById('submit-modal');
const openSubmitModalBtn = document.getElementById('open-submit-modal-btn');
const footerSubmitBtn = document.getElementById('footer-submit-btn');
const heroSubmitBtn = document.getElementById('hero-submit-btn');
const closeSubmitBtn = document.getElementById('close-submit-btn');

const PLACEHOLDER_ART = 'assets/hero_cyberpunk.jpg';

// ---------------------------------------------------------------- boot
async function initGallery() {
  setupEventListeners();

  try {
    const res = await fetch(`community_registry.json?t=${Date.now()}`, { cache: 'no-cache' });
    if (!res.ok) throw new Error(`registry responded ${res.status}`);
    const data = await res.json();
    extensions = Array.isArray(data.extensions) ? data.extensions : [];
  } catch (err) {
    renderLoadError(err);
    return;
  }

  if (extensions.length === 0) {
    renderEmptyState();
    return;
  }

  render();
  fetchLiveCounts();
  openFromHash();
  window.addEventListener('hashchange', openFromHash);
}

// ---------------------------------------------------------------- helpers
function categoriesFor(ext) {
  const values = Array.isArray(ext.tags) ? [...ext.tags] : [];
  if (ext.category) values.push(ext.category);
  return values.map(v => String(v).toLowerCase());
}

function safeUrl(url) {
  if (!url) return '';
  const value = String(url);
  if (/^(https?:)?\/\//i.test(value) || value.startsWith('/')) return value;
  if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return ''; // reject javascript:, data:, etc.
  return value;
}

function artFor(ext) {
  return safeUrl(ext.art_image) || PLACEHOLDER_ART;
}

function installCommandFor(ext) {
  return `safari-magic-ext install ${ext.id}`;
}

const CLI_INSTALLER_URL =
  'https://raw.githubusercontent.com/Vatsal057/safari-magic-extensions/main/install-cli.sh';

function oneLineInstallFor(ext) {
  return `curl -fsSL ${CLI_INSTALLER_URL} | bash -s -- install ${ext.id}`;
}

const FIREBASE_DB_URL = 'https://safari-magic-hub-8679-default-rtdb.firebaseio.com/downloads';
const liveCounts = {};

async function fetchLiveCounts() {
  try {
    const res = await fetch(`${FIREBASE_DB_URL}.json`, { cache: 'no-cache' });
    if (!res.ok) {
      // Usually a rules/permission problem. Warn rather than fail silently:
      // a frozen counter is otherwise indistinguishable from "no downloads yet".
      console.warn(`Live download counts unavailable (HTTP ${res.status}). Showing baseline only.`);
      return;
    }
    const data = await res.json();
    if (data && typeof data === 'object') {
      Object.entries(data).forEach(([slug, count]) => {
        if (typeof count === 'number') {
          liveCounts[slug] = count;
          updateDownloadsUI(slug);
        } else {
          console.warn(`Ignoring non-numeric download count for "${slug}":`, count);
        }
      });
    }
  } catch (err) {
    // Graceful fallback to the static curation baseline.
    console.warn('Could not load live download counts:', err);
  }
}

function getDownloads(ext) {
  if (!ext) return 0;
  const globalCount = liveCounts[ext.id] || 0;
  return (ext.downloads || 0) + globalCount;
}

function formatDownloads(count) {
  if (count >= 1000000) {
    return (count / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
  }
  if (count >= 1000) {
    return (count / 1000).toFixed(1).replace(/\.0$/, '') + 'k';
  }
  return String(count);
}

function trackDownload(extId) {
  if (!extId) return;
  // Optimistic instant UI update
  liveCounts[extId] = (liveCounts[extId] || 0) + 1;
  updateDownloadsUI(extId);

  // Atomic server increment: auto-provisions new extension keys on the fly
  fetch(`${FIREBASE_DB_URL}.json`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      [extId]: { '.sv': { 'increment': 1 } }
    })
  })
    .then(async res => {
      if (!res.ok) throw new Error(`counter responded ${res.status}: ${await res.text()}`);
      return res.json();
    })
    .then(data => {
      if (data && typeof data[extId] === 'number') {
        // Reconcile the optimistic bump with the authoritative server total.
        liveCounts[extId] = data[extId];
        updateDownloadsUI(extId);
      }
    })
    .catch(err => {
      // Keep the optimistic count for this session, but say so: a write that
      // never lands is the difference between a live counter and a frozen one.
      console.warn(`Download count for "${extId}" was not recorded:`, err);
    });
}

function updateDownloadsUI(extId) {
  const ext = extensions.find(e => e.id === extId);
  if (!ext) return;
  const total = getDownloads(ext);
  const formatted = formatDownloads(total);

  const cardBadge = document.querySelector(`.ext-card[data-id="${extId}"] .ext-card-downloads`);
  if (cardBadge) {
    cardBadge.setAttribute('title', `${total.toLocaleString()} downloads`);
    const countSpan = cardBadge.querySelector('.download-count-text');
    if (countSpan) countSpan.textContent = formatted;
  }

  const modalDownloads = document.getElementById('modal-downloads');
  if (modalDownloads && !inspectorModal.classList.contains('hidden')) {
    modalDownloads.innerHTML = `
      <svg class="download-icon" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
      <span>${total.toLocaleString()} downloads</span>
    `;
  }
}

function matchesSearch(ext, query) {
  if (!query) return true;
  const haystack = [
    ext.name, ext.description, ext.prompt, ext.author, ext.id, ext.category,
    ...(Array.isArray(ext.tags) ? ext.tags : []),
  ].filter(Boolean).join(' ').toLowerCase();
  return query.toLowerCase().split(/\s+/).filter(Boolean).every(t => haystack.includes(t));
}

function sortExtensions(list) {
  const copy = [...list];
  const pinOrder = (a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0);

  switch (sortMode) {
    case 'downloads':
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (getDownloads(b) - getDownloads(a)) ||
        (a.name || '').localeCompare(b.name || ''));
    case 'oldest':
      return copy.sort((a, b) => pinOrder(a, b) || (a.added_at || '').localeCompare(b.added_at || ''));
    case 'name':
      return copy.sort((a, b) => pinOrder(a, b) || (a.name || '').localeCompare(b.name || ''));
    case 'author':
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (a.author || '').localeCompare(b.author || '') ||
        (a.name || '').localeCompare(b.name || ''));
    case 'newest':
    default:
      // Pinned first, then most recent; ties fall back to name for a stable order.
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (b.added_at || '').localeCompare(a.added_at || '') ||
        (a.name || '').localeCompare(b.name || ''));
  }
}

function visibleExtensions() {
  const filtered = extensions.filter(
    ext =>
      (activeCategory === 'all' || categoriesFor(ext).includes(activeCategory)) &&
      matchesSearch(ext, searchQuery)
  );
  return sortExtensions(filtered);
}

// ---------------------------------------------------------------- render
function render() {
  const list = visibleExtensions();
  renderCount(list.length);
  renderGrid(list);
}

function renderCount(shown) {
  if (!resultCount) return;
  const total = extensions.length;
  resultCount.textContent =
    shown === total
      ? `${total} extension${total === 1 ? '' : 's'}`
      : `${shown} of ${total} shown`;
}

function renderGrid(list) {
  if (list.length === 0) {
    grid.innerHTML = `
      <p class="grid-empty-note">
        Nothing matches that.
        <button type="button" class="link-inline" id="reset-filters">Clear filters</button>
      </p>`;
    const reset = document.getElementById('reset-filters');
    if (reset) reset.addEventListener('click', resetFilters);
    return;
  }

  grid.innerHTML = list.map(ext => {
    const count = getDownloads(ext);
    const countFormatted = formatDownloads(count);
    return `
    <article class="ext-card ${ext.pinned ? 'ext-card-pinned' : ''}" data-id="${escapeHTML(ext.id)}" role="button" tabindex="0"
             aria-label="${escapeHTML(ext.name)} by ${escapeHTML(ext.author || 'community')}: view install instructions">
      <div class="ext-card-media">
        ${ext.pinned ? '<span class="ext-pinned-badge"><span class="pinned-icon">📌</span> Pinned</span>' : ''}
        <img src="${escapeHTML(artFor(ext))}" alt="Preview of ${escapeHTML(ext.name)}" loading="lazy">
      </div>
      <div class="ext-card-body">
        <h3 class="ext-card-title">${escapeHTML(ext.name)}</h3>
        <p class="ext-card-author">by @${escapeHTML(ext.author || 'community')}</p>
        <p class="ext-card-desc">${escapeHTML(ext.description || '')}</p>
        <div class="ext-card-tags">
          ${(ext.tags || []).map(t => `<button type="button" class="ext-tag" data-tag="${escapeHTML(t)}" title="Filter by #${escapeHTML(t)}">#${escapeHTML(t)}</button>`).join('')}
        </div>
      </div>
      <div class="ext-card-foot">
        <span class="ext-card-downloads" title="${count.toLocaleString()} downloads">
          <svg class="download-icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
          <span class="download-count-text">${countFormatted}</span>
        </span>
        <span class="ext-card-cta">Install →</span>
      </div>
    </article>`;
  }).join('');

  grid.querySelectorAll('.ext-card').forEach(card => {
    const open = () => {
      const item = extensions.find(e => e.id === card.getAttribute('data-id'));
      if (item) openInspector(item);
    };
    card.addEventListener('click', open);
    card.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    });
  });

  grid.querySelectorAll('.ext-tag').forEach(tagBtn => {
    tagBtn.addEventListener('click', e => {
      e.stopPropagation();
      const tag = tagBtn.getAttribute('data-tag');
      if (tag) applyTagFilter(tag);
    });
  });
}

function applyTagFilter(tag) {
  if (!searchInput) return;
  searchInput.value = tag;
  searchQuery = tag.toLowerCase();
  if (searchClear) searchClear.classList.remove('hidden');
  const searchKbd = document.querySelector('.search-kbd');
  if (searchKbd) searchKbd.classList.add('hidden');
  render();
  const galleryEl = document.getElementById('gallery');
  if (galleryEl) galleryEl.scrollIntoView({ behavior: 'smooth' });
}

function renderLoadError(err) {
  console.error('Could not load community_registry.json:', err);
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML = `
    <p class="grid-empty-note">
      Could not load the extension catalog.<br>
      If you opened this file directly, serve it over HTTP instead:
      <code>python3 -m http.server 8000 --directory web</code>
    </p>`;
}

function renderEmptyState() {
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML =
    '<p class="grid-empty-note">No extensions published yet. Be the first to share one.</p>';
}

function resetFilters() {
  activeCategory = 'all';
  searchQuery = '';
  if (searchInput) searchInput.value = '';
  if (searchClear) searchClear.classList.add('hidden');
  const searchKbd = document.querySelector('.search-kbd');
  if (searchKbd) searchKbd.classList.remove('hidden');
  render();
}

// ---------------------------------------------------------------- inspector
function openInspector(ext, { updateHash = true } = {}) {
  modalTitle.textContent = ext.name;
  modalAuthor.textContent = `by @${ext.author || 'community'}`;
  modalCategory.textContent = (ext.category || 'extension').toUpperCase();
  modalImg.src = artFor(ext);
  modalImg.alt = `Preview of ${ext.name}`;
  modalDescription.textContent = ext.description || 'Safari AI Magic Extension';
  modalPrompt.textContent = ext.prompt ? `"${ext.prompt}"` : 'No prompt was recorded for this one.';

  const cliCommand = installCommandFor(ext);
  const oneliner = oneLineInstallFor(ext);
  if (modalCliCmd) modalCliCmd.textContent = cliCommand;
  if (modalOnelinerCmd) modalOnelinerCmd.textContent = oneliner;

  const download = safeUrl(ext.download_url);
  const filename = download.split('/').pop() || `${ext.name}.magicext`;
  modalDownloadPkgBtn.href = download;
  modalDownloadPkgBtn.download = filename;
  if (modalDownloadLabel) modalDownloadLabel.textContent = 'Download .magicext bundle';
  modalDownloadPkgBtn.setAttribute('title', `Download ${filename}`);
  const modalDownloadCmd = document.getElementById('modal-download-cmd');
  if (modalDownloadCmd) {
    modalDownloadCmd.textContent = `safari-magic-ext install ~/Downloads/${filename}`;
  }

  const count = getDownloads(ext);
  const modalDownloads = document.getElementById('modal-downloads');
  if (modalDownloads) {
    modalDownloads.innerHTML = `
      <svg class="download-icon" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
      <span>${count.toLocaleString()} downloads</span>
    `;
  }

  const bits = [`id: ${ext.id}`];
  if (ext.version) bits.push(`v${ext.version}`);
  bits.push(`${count.toLocaleString()} downloads`);
  if (Array.isArray(ext.tags) && ext.tags.length) bits.push(ext.tags.map(t => `#${t}`).join(' '));
  modalMetaRow.textContent = bits.join('  ·  ');

  modalDownloadPkgBtn.onclick = () => {
    trackDownload(ext.id);
  };
  copyModalPromptBtn.onclick = () =>
    copyText(ext.prompt, 'Prompt copied. Paste it into Safari to remix.', copyModalPromptBtn);
  // Copying an install command is not a download. The CLI reports the real
  // install itself once it fetches the package, so counting the copy here
  // would book the same install twice.
  if (copyModalCliBtn) copyModalCliBtn.onclick = () =>
    copyText(cliCommand, 'Install command copied.', copyModalCliBtn);
  if (copyModalOnelinerBtn) copyModalOnelinerBtn.onclick = () =>
    copyText(oneliner, 'One-liner copied!', copyModalOnelinerBtn);

  // Reset install tabs to default (1-Step Install)
  if (installTabOneliner && installTabCli) {
    installTabOneliner.classList.add('active');
    installTabOneliner.setAttribute('aria-selected', 'true');
    installTabCli.classList.remove('active');
    installTabCli.setAttribute('aria-selected', 'false');
    installPaneOneliner.classList.remove('hidden');
    installPaneCli.classList.add('hidden');
  }

  if (updateHash) history.replaceState(null, '', `#ext=${encodeURIComponent(ext.id)}`);
  openModal(inspectorModal);
}

function openFromHash() {
  const hash = window.location.hash;
  if (hash === '#submit') {
    if (submitModal.classList.contains('hidden')) openModal(submitModal);
    return;
  }
  const match = /^#ext=(.+)$/.exec(hash);
  if (!match) return;
  const id = decodeURIComponent(match[1]);
  const ext = extensions.find(e => e.id === id);
  if (ext && inspectorModal.classList.contains('hidden')) {
    openInspector(ext, { updateHash: false });
  }
}

// ---------------------------------------------------------------- modals
function openModal(modal) {
  lastFocusedElement = document.activeElement;
  modal.classList.remove('hidden');
  modal.removeAttribute('aria-hidden');
  document.body.classList.add('modal-open');
  const focusTarget = modal.querySelector('.modal-pixel-close');
  if (focusTarget) focusTarget.focus();
}

function closeModal(modal) {
  modal.classList.add('hidden');
  modal.setAttribute('aria-hidden', 'true');
  document.body.classList.remove('modal-open');
  if (modal === inspectorModal && window.location.hash.startsWith('#ext=')) {
    history.replaceState(null, '', window.location.pathname + window.location.search);
  }
  if (lastFocusedElement && typeof lastFocusedElement.focus === 'function') {
    lastFocusedElement.focus();
    lastFocusedElement = null;
  }
}

function trapFocus(e, modal) {
  if (e.key !== 'Tab') return;
  const focusables = [
    ...modal.querySelectorAll(
      'a[href], button:not([disabled]), input, textarea, select, summary, [tabindex]:not([tabindex="-1"])'
    ),
  ].filter(el => el.offsetParent !== null);
  if (focusables.length === 0) return;
  const first = focusables[0];
  const last = focusables[focusables.length - 1];
  if (e.shiftKey && document.activeElement === first) {
    e.preventDefault();
    last.focus();
  } else if (!e.shiftKey && document.activeElement === last) {
    e.preventDefault();
    first.focus();
  }
}

// ---------------------------------------------------------------- events
function setupEventListeners() {
  if (sortSelect) {
    sortSelect.addEventListener('change', () => {
      sortMode = sortSelect.value;
      render();
    });
  }

  if (modalCategory) {
    modalCategory.style.cursor = 'pointer';
    modalCategory.title = 'Filter by category';
    modalCategory.addEventListener('click', () => {
      const cat = modalCategory.textContent.trim().toLowerCase();
      closeModal(inspectorModal);
      applyTagFilter(cat);
    });
  }

  if (searchInput) {
    const searchKbd = document.querySelector('.search-kbd');
    searchInput.addEventListener('input', () => {
      searchQuery = searchInput.value.trim();
      const hasQuery = searchQuery !== '';
      searchClear.classList.toggle('hidden', !hasQuery);
      if (searchKbd) searchKbd.classList.toggle('hidden', hasQuery);
      render();
    });
    searchInput.addEventListener('keydown', e => {
      if (e.key === 'Escape' && searchInput.value) {
        e.stopPropagation();
        searchInput.value = '';
        searchQuery = '';
        searchClear.classList.add('hidden');
        if (searchKbd) searchKbd.classList.remove('hidden');
        render();
      }
    });
  }
  if (searchClear) {
    searchClear.addEventListener('click', () => {
      const searchKbd = document.querySelector('.search-kbd');
      searchInput.value = '';
      searchQuery = '';
      searchClear.classList.add('hidden');
      if (searchKbd) searchKbd.classList.remove('hidden');
      searchInput.focus();
      render();
    });
  }

  closeInspectorBtn.addEventListener('click', () => closeModal(inspectorModal));
  inspectorModal.addEventListener('click', e => {
    if (e.target === inspectorModal) closeModal(inspectorModal);
  });
  inspectorModal.addEventListener('keydown', e => trapFocus(e, inspectorModal));
  if (modalSetupLink) modalSetupLink.addEventListener('click', () => closeModal(inspectorModal));

  // Install modal tab switcher
  if (installTabOneliner && installTabCli) {
    function switchInstallTab(toOneliner) {
      installTabOneliner.classList.toggle('active', toOneliner);
      installTabOneliner.setAttribute('aria-selected', String(toOneliner));
      installTabCli.classList.toggle('active', !toOneliner);
      installTabCli.setAttribute('aria-selected', String(!toOneliner));
      installPaneOneliner.classList.toggle('hidden', !toOneliner);
      installPaneCli.classList.toggle('hidden', toOneliner);
    }
    installTabOneliner.addEventListener('click', () => switchInstallTab(true));
    installTabCli.addEventListener('click', () => switchInstallTab(false));
  }

  const openSubmit = () => {
    const stabCli = document.getElementById('stab-cli');
    const stabFinder = document.getElementById('stab-nonterminal');
    const paneCli = document.getElementById('submit-pane-cli');
    const paneFinder = document.getElementById('submit-pane-nonterminal');
    if (stabCli && stabFinder && paneCli && paneFinder) {
      stabCli.classList.add('active');
      stabCli.setAttribute('aria-selected', 'true');
      stabFinder.classList.remove('active');
      stabFinder.setAttribute('aria-selected', 'false');
      paneCli.classList.remove('hidden');
      paneFinder.classList.add('hidden');
    }
    openModal(submitModal);
  };
  [openSubmitModalBtn, footerSubmitBtn, heroSubmitBtn].forEach(btn => {
    if (btn) btn.addEventListener('click', openSubmit);
  });
  if (closeSubmitBtn) closeSubmitBtn.addEventListener('click', () => closeModal(submitModal));
  submitModal.addEventListener('click', e => {
    if (e.target === submitModal) closeModal(submitModal);
  });
  submitModal.addEventListener('keydown', e => trapFocus(e, submitModal));

  // Submit modal tab switcher
  const submitTabs = [
    { btn: document.getElementById('stab-cli'),         pane: document.getElementById('submit-pane-cli') },
    { btn: document.getElementById('stab-nonterminal'), pane: document.getElementById('submit-pane-nonterminal') },
  ];
  submitTabs.forEach(({ btn, pane }) => {
    if (!btn || !pane) return;
    btn.addEventListener('click', () => {
      submitTabs.forEach(({ btn: b, pane: p }) => {
        if (!b || !p) return;
        b.classList.remove('active');
        b.setAttribute('aria-selected', 'false');
        p.classList.add('hidden');
      });
      btn.classList.add('active');
      btn.setAttribute('aria-selected', 'true');
      pane.classList.remove('hidden');
    });
  });

  // Submit dropzone logic
  setupDropzone();

  document.addEventListener('keydown', e => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
      e.preventDefault();
      if (searchInput) {
        searchInput.focus();
        searchInput.select();
      }
      return;
    }
    if (e.key !== 'Escape') return;
    if (!inspectorModal.classList.contains('hidden')) closeModal(inspectorModal);
    if (!submitModal.classList.contains('hidden')) closeModal(submitModal);
  });

  // Generic copy buttons (data-copy-target)
  document.addEventListener('click', e => {
    const btn = e.target.closest('[data-copy-target]');
    if (!btn) return;
    const targetEl = document.getElementById(btn.dataset.copyTarget);
    if (targetEl) {
      copyText(targetEl.textContent, btn.dataset.copyLabel || 'Copied!', btn);
    }
  });
}

// ---------------------------------------------------------------- utilities
function copyText(text, successMsg, triggerBtn) {
  if (!text) return;
  const cleanText = text.trim();

  const onCopySuccess = () => {
    showToast(successMsg || 'Copied to clipboard.');
    if (triggerBtn) flashCopiedButton(triggerBtn);
  };

  const onCopyFailure = () => {
    showToast('Could not copy. Select the text and copy manually.');
  };

  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(cleanText)
      .then(onCopySuccess)
      .catch(() => {
        if (execFallback(cleanText)) {
          onCopySuccess();
        } else {
          onCopyFailure();
        }
      });
    return;
  }

  if (execFallback(cleanText)) {
    onCopySuccess();
  } else {
    onCopyFailure();
  }
}

function execFallback(cleanText) {
  const ta = document.createElement('textarea');
  ta.value = cleanText;
  ta.style.position = 'fixed';
  ta.style.top = '0';
  ta.style.left = '0';
  ta.style.width = '2em';
  ta.style.height = '2em';
  ta.style.padding = '0';
  ta.style.border = 'none';
  ta.style.outline = 'none';
  ta.style.boxShadow = 'none';
  ta.style.background = 'transparent';
  ta.style.color = 'transparent';
  ta.style.opacity = '0.01';
  ta.style.zIndex = '-9999';
  document.body.appendChild(ta);
  ta.focus();
  ta.select();
  ta.setSelectionRange(0, cleanText.length);

  let ok = false;
  try {
    ok = document.execCommand('copy');
  } catch (err) {
    ok = false;
  }
  document.body.removeChild(ta);
  return ok;
}

function flashCopiedButton(btn) {
  if (!btn || btn.dataset.copying) return;
  btn.dataset.copying = 'true';
  const originalHtml = btn.innerHTML;
  btn.classList.add('is-copied');
  btn.textContent = 'copied!';
  setTimeout(() => {
    btn.innerHTML = originalHtml;
    btn.classList.remove('is-copied');
    delete btn.dataset.copying;
  }, 1800);
}

let toastTimer = null;
function showToast(msg) {
  toastEl.textContent = msg;
  toastEl.classList.remove('hidden');
  if (toastTimer) clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toastEl.classList.add('hidden'), 2600);
}

function escapeHTML(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ---------------------------------------------------------------- dropzone
const GITHUB_REPO = 'Vatsal057/safari-magic-extensions';

function setupDropzone() {
  const dropzone = document.getElementById('submit-dropzone');
  const folderInput = document.getElementById('submit-folder-input');
  const preview = document.getElementById('submit-preview');
  if (!dropzone || !folderInput || !preview) return;

  dropzone.addEventListener('dragover', e => {
    e.preventDefault();
    dropzone.classList.add('dropzone-over');
  });
  dropzone.addEventListener('dragleave', () => dropzone.classList.remove('dropzone-over'));
  dropzone.addEventListener('drop', e => {
    e.preventDefault();
    dropzone.classList.remove('dropzone-over');
    const items = [...(e.dataTransfer.items || [])];
    const entries = items.map(i => i.webkitGetAsEntry && i.webkitGetAsEntry()).filter(Boolean);
    if (entries.length) {
      processDroppedEntries(entries);
    } else if (e.dataTransfer.files.length) {
      processFileList(e.dataTransfer.files);
    }
  });
  dropzone.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') folderInput.click();
  });

  folderInput.addEventListener('change', () => {
    if (folderInput.files.length) processFileList(folderInput.files);
  });

  async function processDroppedEntries(entries) {
    const allFiles = [];
    for (const entry of entries) {
      await collectFiles(entry, allFiles);
    }
    await buildPreviewFromFiles(allFiles);
  }

  function processFileList(fileList) {
    buildPreviewFromFiles([...fileList]);
  }

  function collectFiles(entry, collector) {
    return new Promise(resolve => {
      if (entry.isFile) {
        entry.getFile(f => { collector.push(f); resolve(); });
      } else if (entry.isDirectory) {
        const reader = entry.createReader();
        reader.readEntries(async subEntries => {
          for (const sub of subEntries) await collectFiles(sub, collector);
          resolve();
        });
      } else {
        resolve();
      }
    });
  }

  async function buildPreviewFromFiles(files) {
    // Find manifest.json anywhere in the dropped set.
    const manifestFile = files.find(f => f.name === 'manifest.json');
    if (!manifestFile) {
      showToast('Could not find manifest.json in that folder. Is this a Safari extension?');
      return;
    }

    let manifest;
    try {
      const text = await manifestFile.text();
      manifest = JSON.parse(text);
    } catch {
      showToast('manifest.json is not valid JSON.');
      return;
    }

    const name = manifest.name || 'My Extension';
    const prompt = manifest.browser_specific_settings?.safari?.prompt || manifest.description || '';
    const iconStr = manifest.icon_variants?.[0]?.any || '';
    const symbol = iconStr.startsWith('symbol:') ? iconStr.slice(7) : iconStr;
    const description = manifest.description || '';

    // Build GitHub pre-filled issue URL.
    const params = new URLSearchParams({
      template: 'extension_submission.yml',
      title: `[Extension Submission]: ${name}`,
      extension_name: name,
      ai_prompt: prompt,
      description,
      selected_symbol: symbol,
    });
    const ghUrl = `https://github.com/${GITHUB_REPO}/issues/new?${params.toString()}`;

    // Show preview.
    document.getElementById('preview-name').textContent = name;
    document.getElementById('preview-prompt').textContent = prompt ? `"${prompt}"` : '';
    document.getElementById('preview-icon').textContent = symbol ? '🪄' : '📦';
    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '_') || 'Extension';
    const filename = `${safeName}.magicext`;
    const previewFilename = document.getElementById('preview-filename');
    if (previewFilename) previewFilename.textContent = filename;
    document.getElementById('submit-github-btn').href = ghUrl;

    preview.classList.remove('hidden');
    dropzone.classList.add('dropzone-done');
    showToast(`Found "${name}". Click Submit to GitHub to open the form.`);
  }
}

document.addEventListener('DOMContentLoaded', initGallery);

