/**
 * Safari Magic Gallery: gallery logic.
 *
 * Data comes from community_registry.json, generated by scripts/build_registry.py.
 * Every extension is presented equally in one grid; users choose the order with
 * the sort control. Thumbnails are real screenshots (see generate_thumbnails.sh).
 */

// ---------------------------------------------------------------- state
let extensions = [];
let activeCategory = 'all';
let searchQuery = '';
let sortMode = 'newest';

let lastFocusedElement = null;

// ---------------------------------------------------------------- elements
const grid = document.getElementById('extension-grid');
const toastEl = document.getElementById('toast');
const searchInput = document.getElementById('search-input');
const searchClear = document.getElementById('search-clear');
const sortSelect = document.getElementById('sort-select');
const resultCount = document.getElementById('result-count');

const inspectorModal = document.getElementById('inspector-modal');
const closeInspectorBtn = document.getElementById('close-inspector-btn');
const modalTitle = document.getElementById('modal-title');
const modalAuthor = document.getElementById('modal-author');
const modalCategory = document.getElementById('modal-category');
const modalImg = document.getElementById('modal-img');
const modalDescription = document.getElementById('modal-description');
const modalPrompt = document.getElementById('modal-prompt');
const modalCliCmd = document.getElementById('modal-cli-cmd');
const modalOnelinerCmd = document.getElementById('modal-oneliner-cmd');
const copyModalOnelinerBtn = document.getElementById('copy-modal-oneliner-btn');
const modalDownloadPkgBtn = document.getElementById('modal-download-pkg-btn');
const modalDownloadLabel = document.getElementById('modal-download-label');
const modalMetaRow = document.getElementById('modal-meta-row');
const modalSetupLink = document.getElementById('modal-setup-link');
const copyModalPromptBtn = document.getElementById('copy-modal-prompt-btn');
const copyModalCliBtn = document.getElementById('copy-modal-cli-btn');

// Install tab switcher elements
const installTabOneliner = document.getElementById('tab-oneliner');
const installTabCli = document.getElementById('tab-cli');
const installPaneOneliner = document.getElementById('install-pane-oneliner');
const installPaneCli = document.getElementById('install-pane-cli');

const submitModal = document.getElementById('submit-modal');
const openSubmitModalBtn = document.getElementById('open-submit-modal-btn');
const footerSubmitBtn = document.getElementById('footer-submit-btn');
const heroSubmitBtn = document.getElementById('hero-submit-btn');
const closeSubmitBtn = document.getElementById('close-submit-btn');

const PLACEHOLDER_ART = 'assets/hero_cyberpunk.jpg';

// ---------------------------------------------------------------- boot
async function initGallery() {
  setupEventListeners();

  try {
    const res = await fetch(`community_registry.json?t=${Date.now()}`, { cache: 'no-cache' });
    if (!res.ok) throw new Error(`registry responded ${res.status}`);
    const data = await res.json();
    extensions = Array.isArray(data.extensions) ? data.extensions : [];
  } catch (err) {
    renderLoadError(err);
    return;
  }

  if (extensions.length === 0) {
    renderEmptyState();
    return;
  }

  render();
  fetchLiveCounts();
  openFromHash();
  window.addEventListener('hashchange', openFromHash);
}

// ---------------------------------------------------------------- helpers
function categoriesFor(ext) {
  const values = Array.isArray(ext.tags) ? [...ext.tags] : [];
  if (ext.category) values.push(ext.category);
  return values.map(v => String(v).toLowerCase());
}

function safeUrl(url) {
  if (!url) return '';
  const value = String(url);
  if (/^(https?:)?\/\//i.test(value) || value.startsWith('/')) return value;
  if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return ''; // reject javascript:, data:, etc.
  return value;
}

function artFor(ext) {
  return safeUrl(ext.art_image) || PLACEHOLDER_ART;
}

function installCommandFor(ext) {
  return `safari-magic-ext install ${ext.id}`;
}

const CLI_INSTALLER_URL =
  'https://raw.githubusercontent.com/Vatsal057/safari-magic-extensions/main/install-cli.sh';

function oneLineInstallFor(ext) {
  return `curl -fsSL ${CLI_INSTALLER_URL} | bash -s -- install ${ext.id}`;
}

const FIREBASE_DB_URL = 'https://safari-magic-hub-8679-default-rtdb.firebaseio.com/downloads';
const liveCounts = {};

async function fetchLiveCounts() {
  try {
    const res = await fetch(`${FIREBASE_DB_URL}.json`, { cache: 'no-cache' });
    if (!res.ok) {
      // Usually a rules/permission problem. Warn rather than fail silently:
      // a frozen counter is otherwise indistinguishable from "no downloads yet".
      console.warn(`Live download counts unavailable (HTTP ${res.status}). Showing baseline only.`);
      return;
    }
    const data = await res.json();
    if (data && typeof data === 'object') {
      Object.entries(data).forEach(([slug, count]) => {
        if (typeof count === 'number') {
          liveCounts[slug] = count;
          updateDownloadsUI(slug);
        } else {
          console.warn(`Ignoring non-numeric download count for "${slug}":`, count);
        }
      });
    }
  } catch (err) {
    // Graceful fallback to the static curation baseline.
    console.warn('Could not load live download counts:', err);
  }
}

function getDownloads(ext) {
  if (!ext) return 0;
  const globalCount = liveCounts[ext.id] || 0;
  return (ext.downloads || 0) + globalCount;
}

function formatDownloads(count) {
  if (count >= 1000000) {
    return (count / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
  }
  if (count >= 1000) {
    return (count / 1000).toFixed(1).replace(/\.0$/, '') + 'k';
  }
  return String(count);
}

function trackDownload(extId) {
  if (!extId) return;
  // Optimistic instant UI update
  liveCounts[extId] = (liveCounts[extId] || 0) + 1;
  updateDownloadsUI(extId);

  // Atomic server increment: auto-provisions new extension keys on the fly
  fetch(`${FIREBASE_DB_URL}.json`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      [extId]: { '.sv': { 'increment': 1 } }
    })
  })
    .then(async res => {
      if (!res.ok) throw new Error(`counter responded ${res.status}: ${await res.text()}`);
      return res.json();
    })
    .then(data => {
      if (data && typeof data[extId] === 'number') {
        // Reconcile the optimistic bump with the authoritative server total.
        liveCounts[extId] = data[extId];
        updateDownloadsUI(extId);
      }
    })
    .catch(err => {
      // Keep the optimistic count for this session, but say so: a write that
      // never lands is the difference between a live counter and a frozen one.
      console.warn(`Download count for "${extId}" was not recorded:`, err);
    });
}

function updateDownloadsUI(extId) {
  const ext = extensions.find(e => e.id === extId);
  if (!ext) return;
  const total = getDownloads(ext);
  const formatted = formatDownloads(total);

  const cardBadge = document.querySelector(`.ext-card[data-id="${extId}"] .ext-card-downloads`);
  if (cardBadge) {
    cardBadge.setAttribute('title', `${total.toLocaleString()} downloads`);
    const countSpan = cardBadge.querySelector('.download-count-text');
    if (countSpan) countSpan.textContent = formatted;
  }

  const modalDownloads = document.getElementById('modal-downloads');
  if (modalDownloads && !inspectorModal.classList.contains('hidden')) {
    modalDownloads.innerHTML = `
      <svg class="download-icon" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
      <span>${total.toLocaleString()} downloads</span>
    `;
  }
}

function matchesSearch(ext, query) {
  if (!query) return true;
  const haystack = [
    ext.name, ext.description, ext.prompt, ext.author, ext.id, ext.category,
    ...(Array.isArray(ext.tags) ? ext.tags : []),
  ].filter(Boolean).join(' ').toLowerCase();
  return query.toLowerCase().split(/\s+/).filter(Boolean).every(t => haystack.includes(t));
}

function sortExtensions(list) {
  const copy = [...list];
  const pinOrder = (a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0);

  switch (sortMode) {
    case 'downloads':
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (getDownloads(b) - getDownloads(a)) ||
        (a.name || '').localeCompare(b.name || ''));
    case 'oldest':
      return copy.sort((a, b) => pinOrder(a, b) || (a.added_at || '').localeCompare(b.added_at || ''));
    case 'name':
      return copy.sort((a, b) => pinOrder(a, b) || (a.name || '').localeCompare(b.name || ''));
    case 'author':
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (a.author || '').localeCompare(b.author || '') ||
        (a.name || '').localeCompare(b.name || ''));
    case 'newest':
    default:
      // Pinned first, then most recent; ties fall back to name for a stable order.
      return copy.sort((a, b) =>
        pinOrder(a, b) ||
        (b.added_at || '').localeCompare(a.added_at || '') ||
        (a.name || '').localeCompare(b.name || ''));
  }
}

function visibleExtensions() {
  const filtered = extensions.filter(
    ext =>
      (activeCategory === 'all' || categoriesFor(ext).includes(activeCategory)) &&
      matchesSearch(ext, searchQuery)
  );
  return sortExtensions(filtered);
}

// ---------------------------------------------------------------- render
function render() {
  const list = visibleExtensions();
  renderCount(list.length);
  renderGrid(list);
}

function renderCount(shown) {
  if (!resultCount) return;
  const total = extensions.length;
  resultCount.textContent =
    shown === total
      ? `${total} extension${total === 1 ? '' : 's'}`
      : `${shown} of ${total} shown`;
}

function renderGrid(list) {
  if (list.length === 0) {
    grid.innerHTML = `
      <p class="grid-empty-note">
        Nothing matches that.
        <button type="button" class="link-inline" id="reset-filters">Clear filters</button>
      </p>`;
    const reset = document.getElementById('reset-filters');
    if (reset) reset.addEventListener('click', resetFilters);
    return;
  }

  grid.innerHTML = list.map(ext => {
    const count = getDownloads(ext);
    const countFormatted = formatDownloads(count);
    return `
    <article class="ext-card ${ext.pinned ? 'ext-card-pinned' : ''}" data-id="${escapeHTML(ext.id)}" role="button" tabindex="0"
             aria-label="${escapeHTML(ext.name)} by ${escapeHTML(ext.author || 'community')}: view install instructions">
      <div class="ext-card-media">
        ${ext.pinned ? '<span class="ext-pinned-badge"><span class="pinned-icon">📌</span> Pinned</span>' : ''}
        <img src="${escapeHTML(artFor(ext))}" alt="Preview of ${escapeHTML(ext.name)}" loading="lazy">
      </div>
      <div class="ext-card-body">
        <h3 class="ext-card-title">${escapeHTML(ext.name)}</h3>
        <p class="ext-card-author">by @${escapeHTML(ext.author || 'community')}</p>
        <p class="ext-card-desc">${escapeHTML(ext.description || '')}</p>
        <div class="ext-card-tags">
          ${(ext.tags || []).map(t => `<button type="button" class="ext-tag" data-tag="${escapeHTML(t)}" title="Filter by #${escapeHTML(t)}">#${escapeHTML(t)}</button>`).join('')}
        </div>
      </div>
      <div class="ext-card-foot">
        <span class="ext-card-downloads" title="${count.toLocaleString()} downloads">
          <svg class="download-icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
          <span class="download-count-text">${countFormatted}</span>
        </span>
        <span class="ext-card-cta">Install →</span>
      </div>
    </article>`;
  }).join('');

  grid.querySelectorAll('.ext-card').forEach(card => {
    const open = () => {
      const item = extensions.find(e => e.id === card.getAttribute('data-id'));
      if (item) openInspector(item);
    };
    card.addEventListener('click', open);
    card.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    });
  });

  grid.querySelectorAll('.ext-tag').forEach(tagBtn => {
    tagBtn.addEventListener('click', e => {
      e.stopPropagation();
      const tag = tagBtn.getAttribute('data-tag');
      if (tag) applyTagFilter(tag);
    });
  });
}

function applyTagFilter(tag) {
  if (!searchInput) return;
  searchInput.value = tag;
  searchQuery = tag.toLowerCase();
  if (searchClear) searchClear.classList.remove('hidden');
  const searchKbd = document.querySelector('.search-kbd');
  if (searchKbd) searchKbd.classList.add('hidden');
  render();
  const galleryEl = document.getElementById('gallery');
  if (galleryEl) galleryEl.scrollIntoView({ behavior: 'smooth' });
}

function renderLoadError(err) {
  console.error('Could not load community_registry.json:', err);
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML = `
    <p class="grid-empty-note">
      Could not load the extension catalog.<br>
      If you opened this file directly, serve it over HTTP instead:
      <code>python3 -m http.server 8000 --directory web</code>
    </p>`;
}

function renderEmptyState() {
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML =
    '<p class="grid-empty-note">No extensions published yet. Be the first to share one.</p>';
}

function resetFilters() {
  activeCategory = 'all';
  searchQuery = '';
  if (searchInput) searchInput.value = '';
  if (searchClear) searchClear.classList.add('hidden');
  const searchKbd = document.querySelector('.search-kbd');
  if (searchKbd) searchKbd.classList.remove('hidden');
  render();
}

// ---------------------------------------------------------------- inspector
function openInspector(ext, { updateHash = true } = {}) {
  modalTitle.textContent = ext.name;
  modalAuthor.textContent = `by @${ext.author || 'community'}`;
  modalCategory.textContent = (ext.category || 'extension').toUpperCase();
  modalImg.src = artFor(ext);
  modalImg.alt = `Preview of ${ext.name}`;
  modalDescription.textContent = ext.description || 'Safari AI Magic Extension';
  modalPrompt.textContent = ext.prompt ? `"${ext.prompt}"` : 'No prompt was recorded for this one.';

  const cliCommand = installCommandFor(ext);
  const oneliner = oneLineInstallFor(ext);
  if (modalCliCmd) modalCliCmd.textContent = cliCommand;
  if (modalOnelinerCmd) modalOnelinerCmd.textContent = oneliner;

  const download = safeUrl(ext.download_url);
  const filename = download.split('/').pop() || `${ext.name}.magicext`;
  modalDownloadPkgBtn.href = download;
  modalDownloadPkgBtn.download = filename;
  if (modalDownloadLabel) modalDownloadLabel.textContent = 'Download .magicext bundle';
  modalDownloadPkgBtn.setAttribute('title', `Download ${filename}`);
  const modalDownloadCmd = document.getElementById('modal-download-cmd');
  if (modalDownloadCmd) {
    modalDownloadCmd.textContent = `safari-magic-ext install ~/Downloads/${filename}`;
  }

  const count = getDownloads(ext);
  const modalDownloads = document.getElementById('modal-downloads');
  if (modalDownloads) {
    modalDownloads.innerHTML = `
      <svg class="download-icon" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
      <span>${count.toLocaleString()} downloads</span>
    `;
  }

  const bits = [`id: ${ext.id}`];
  if (ext.version) bits.push(`v${ext.version}`);
  bits.push(`${count.toLocaleString()} downloads`);
  if (Array.isArray(ext.tags) && ext.tags.length) bits.push(ext.tags.map(t => `#${t}`).join(' '));
  modalMetaRow.textContent = bits.join('  ·  ');

  modalDownloadPkgBtn.onclick = () => {
    trackDownload(ext.id);
  };
  copyModalPromptBtn.onclick = () =>
    copyText(ext.prompt, 'Prompt copied. Paste it into Safari to remix.', copyModalPromptBtn);
  // Copying an install command is not a download. The CLI reports the real
  // install itself once it fetches the package, so counting the copy here
  // would book the same install twice.
  if (copyModalCliBtn) copyModalCliBtn.onclick = () =>
    copyText(cliCommand, 'Install command copied.', copyModalCliBtn);
  if (copyModalOnelinerBtn) copyModalOnelinerBtn.onclick = () =>
    copyText(oneliner, 'One-liner copied!', copyModalOnelinerBtn);

  // Reset install tabs to default (1-Step Install)
  if (installTabOneliner && installTabCli) {
    installTabOneliner.classList.add('active');
    installTabOneliner.setAttribute('aria-selected', 'true');
    installTabCli.classList.remove('active');
    installTabCli.setAttribute('aria-selected', 'false');
    installPaneOneliner.classList.remove('hidden');
    installPaneCli.classList.add('hidden');
  }

  if (updateHash) history.replaceState(null, '', `#ext=${encodeURIComponent(ext.id)}`);
  openModal(inspectorModal);
}

function openFromHash() {
  const hash = window.location.hash;
  if (hash === '#submit') {
    if (submitModal.classList.contains('hidden')) openModal(submitModal);
    return;
  }
  const match = /^#ext=(.+)$/.exec(hash);
  if (!match) return;
  const id = decodeURIComponent(match[1]);
  const ext = extensions.find(e => e.id === id);
  if (ext && inspectorModal.classList.contains('hidden')) {
    openInspector(ext, { updateHash: false });
  }
}

// ---------------------------------------------------------------- modals
function openModal(modal) {
  lastFocusedElement = document.activeElement;
  modal.classList.remove('hidden');
  modal.removeAttribute('aria-hidden');
  document.body.classList.add('modal-open');
  const focusTarget = modal.querySelector('.modal-pixel-close');
  if (focusTarget) focusTarget.focus();
}

function closeModal(modal) {
  modal.classList.add('hidden');
  modal.setAttribute('aria-hidden', 'true');
  document.body.classList.remove('modal-open');
  if (modal === inspectorModal && window.location.hash.startsWith('#ext=')) {
    history.replaceState(null, '', window.location.pathname + window.location.search);
  }
  if (lastFocusedElement && typeof lastFocusedElement.focus === 'function') {
    lastFocusedElement.focus();
    lastFocusedElement = null;
  }
}

function trapFocus(e, modal) {
  if (e.key !== 'Tab') return;
  const focusables = [
    ...modal.querySelectorAll(
      'a[href], button:not([disabled]), input, textarea, select, summary, [tabindex]:not([tabindex="-1"])'
    ),
  ].filter(el => el.offsetParent !== null);
  if (focusables.length === 0) return;
  const first = focusables[0];
  const last = focusables[focusables.length - 1];
  if (e.shiftKey && document.activeElement === first) {
    e.preventDefault();
    last.focus();
  } else if (!e.shiftKey && document.activeElement === last) {
    e.preventDefault();
    first.focus();
  }
}

// ---------------------------------------------------------------- events
function setupEventListeners() {
  if (sortSelect) {
    sortSelect.addEventListener('change', () => {
      sortMode = sortSelect.value;
      render();
    });
  }

  if (modalCategory) {
    modalCategory.style.cursor = 'pointer';
    modalCategory.title = 'Filter by category';
    modalCategory.addEventListener('click', () => {
      const cat = modalCategory.textContent.trim().toLowerCase();
      closeModal(inspectorModal);
      applyTagFilter(cat);
    });
  }

  if (searchInput) {
    const searchKbd = document.querySelector('.search-kbd');
    searchInput.addEventListener('input', () => {
      searchQuery = searchInput.value.trim();
      const hasQuery = searchQuery !== '';
      searchClear.classList.toggle('hidden', !hasQuery);
      if (searchKbd) searchKbd.classList.toggle('hidden', hasQuery);
      render();
    });
    searchInput.addEventListener('keydown', e => {
      if (e.key === 'Escape' && searchInput.value) {
        e.stopPropagation();
        searchInput.value = '';
        searchQuery = '';
        searchClear.classList.add('hidden');
        if (searchKbd) searchKbd.classList.remove('hidden');
        render();
      }
    });
  }
  if (searchClear) {
    searchClear.addEventListener('click', () => {
      const searchKbd = document.querySelector('.search-kbd');
      searchInput.value = '';
      searchQuery = '';
      searchClear.classList.add('hidden');
      if (searchKbd) searchKbd.classList.remove('hidden');
      searchInput.focus();
      render();
    });
  }

  closeInspectorBtn.addEventListener('click', () => closeModal(inspectorModal));
  inspectorModal.addEventListener('click', e => {
    if (e.target === inspectorModal) closeModal(inspectorModal);
  });
  inspectorModal.addEventListener('keydown', e => trapFocus(e, inspectorModal));
  if (modalSetupLink) modalSetupLink.addEventListener('click', () => closeModal(inspectorModal));

  // Install modal tab switcher
  if (installTabOneliner && installTabCli) {
    function switchInstallTab(toOneliner) {
      installTabOneliner.classList.toggle('active', toOneliner);
      installTabOneliner.setAttribute('aria-selected', String(toOneliner));
      installTabCli.classList.toggle('active', !toOneliner);
      installTabCli.setAttribute('aria-selected', String(!toOneliner));
      installPaneOneliner.classList.toggle('hidden', !toOneliner);
      installPaneCli.classList.toggle('hidden', toOneliner);
    }
    installTabOneliner.addEventListener('click', () => switchInstallTab(true));
    installTabCli.addEventListener('click', () => switchInstallTab(false));
  }

  const openSubmit = () => {
    const stabCli = document.getElementById('stab-cli');
    const stabFinder = document.getElementById('stab-nonterminal');
    const paneCli = document.getElementById('submit-pane-cli');
    const paneFinder = document.getElementById('submit-pane-nonterminal');
    if (stabCli && stabFinder && paneCli && paneFinder) {
      stabCli.classList.add('active');
      stabCli.setAttribute('aria-selected', 'true');
      stabFinder.classList.remove('active');
      stabFinder.setAttribute('aria-selected', 'false');
      paneCli.classList.remove('hidden');
      paneFinder.classList.add('hidden');
    }
    openModal(submitModal);
  };
  [openSubmitModalBtn, footerSubmitBtn, heroSubmitBtn].forEach(btn => {
    if (btn) btn.addEventListener('click', openSubmit);
  });
  if (closeSubmitBtn) closeSubmitBtn.addEventListener('click', () => closeModal(submitModal));
  submitModal.addEventListener('click', e => {
    if (e.target === submitModal) closeModal(submitModal);
  });
  submitModal.addEventListener('keydown', e => trapFocus(e, submitModal));

  // Submit modal tab switcher
  const submitTabs = [
    { btn: document.getElementById('stab-cli'),         pane: document.getElementById('submit-pane-cli') },
    { btn: document.getElementById('stab-nonterminal'), pane: document.getElementById('submit-pane-nonterminal') },
  ];
  submitTabs.forEach(({ btn, pane }) => {
    if (!btn || !pane) return;
    btn.addEventListener('click', () => {
      submitTabs.forEach(({ btn: b, pane: p }) => {
        if (!b || !p) return;
        b.classList.remove('active');
        b.setAttribute('aria-selected', 'false');
        p.classList.add('hidden');
      });
      btn.classList.add('active');
      btn.setAttribute('aria-selected', 'true');
      pane.classList.remove('hidden');
    });
  });

  // Submit dropzone logic
  setupDropzone();

  document.addEventListener('keydown', e => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
      e.preventDefault();
      if (searchInput) {
        searchInput.focus();
        searchInput.select();
      }
      return;
    }
    if (e.key !== 'Escape') return;
    if (!inspectorModal.classList.contains('hidden')) closeModal(inspectorModal);
    if (!submitModal.classList.contains('hidden')) closeModal(submitModal);
  });

  // Generic copy buttons (data-copy-target)
  document.addEventListener('click', e => {
    const btn = e.target.closest('[data-copy-target]');
    if (!btn) return;
    const targetEl = document.getElementById(btn.dataset.copyTarget);
    if (targetEl) {
      copyText(targetEl.textContent, btn.dataset.copyLabel || 'Copied!', btn);
    }
  });
}

// ---------------------------------------------------------------- utilities
function copyText(text, successMsg, triggerBtn) {
  if (!text) return;
  const cleanText = text.trim();

  const onCopySuccess = () => {
    showToast(successMsg || 'Copied to clipboard.');
    if (triggerBtn) flashCopiedButton(triggerBtn);
  };

  const onCopyFailure = () => {
    showToast('Could not copy. Select the text and copy manually.');
  };

  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(cleanText)
      .then(onCopySuccess)
      .catch(() => {
        if (execFallback(cleanText)) {
          onCopySuccess();
        } else {
          onCopyFailure();
        }
      });
    return;
  }

  if (execFallback(cleanText)) {
    onCopySuccess();
  } else {
    onCopyFailure();
  }
}

function execFallback(cleanText) {
  const ta = document.createElement('textarea');
  ta.value = cleanText;
  ta.style.position = 'fixed';
  ta.style.top = '0';
  ta.style.left = '0';
  ta.style.width = '2em';
  ta.style.height = '2em';
  ta.style.padding = '0';
  ta.style.border = 'none';
  ta.style.outline = 'none';
  ta.style.boxShadow = 'none';
  ta.style.background = 'transparent';
  ta.style.color = 'transparent';
  ta.style.opacity = '0.01';
  ta.style.zIndex = '-9999';
  document.body.appendChild(ta);
  ta.focus();
  ta.select();
  ta.setSelectionRange(0, cleanText.length);

  let ok = false;
  try {
    ok = document.execCommand('copy');
  } catch (err) {
    ok = false;
  }
  document.body.removeChild(ta);
  return ok;
}

function flashCopiedButton(btn) {
  if (!btn || btn.dataset.copying) return;
  btn.dataset.copying = 'true';
  const originalHtml = btn.innerHTML;
  btn.classList.add('is-copied');
  btn.textContent = 'copied!';
  setTimeout(() => {
    btn.innerHTML = originalHtml;
    btn.classList.remove('is-copied');
    delete btn.dataset.copying;
  }, 1800);
}

let toastTimer = null;
function showToast(msg) {
  toastEl.textContent = msg;
  toastEl.classList.remove('hidden');
  if (toastTimer) clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toastEl.classList.add('hidden'), 2600);
}

function escapeHTML(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ---------------------------------------------------------------- dropzone & zip engine
const GITHUB_REPO = 'Vatsal057/safari-magic-extensions';

const IGNORE_PATTERNS = [
  /^\./,             // hidden files / folders (.DS_Store, .git, etc.)
  /^__MACOSX/i,
  /^node_modules/i,
  /Thumbs\.db/i,
  /\.tmp$/i,
  /\.vscode/i,
];

// Precomputed CRC32 table
const CRC_TABLE = new Uint32Array(256);
for (let n = 0; n < 256; n++) {
  let c = n;
  for (let k = 0; k < 8; k++) {
    c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
  }
  CRC_TABLE[n] = c >>> 0;
}

function calcCrc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) {
    c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  }
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function toDosDateTime(date) {
  const d = date || new Date();
  const time = (d.getHours() << 11) | (d.getMinutes() << 5) | (d.getSeconds() >> 1);
  const dt = ((d.getFullYear() - 1980) << 9) | ((d.getMonth() + 1) << 5) | d.getDate();
  return { time, date: dt };
}

async function createZipArchive(entries) {
  const localHeaders = [];
  const centralHeaders = [];
  let offset = 0;

  for (const entry of entries) {
    const rawData = entry.data;
    const pathBytes = new TextEncoder().encode(entry.path);
    const crc = calcCrc32(rawData);

    let compData = rawData;
    let method = 0; // STORE

    // Attempt DEFLATE compression if modern CompressionStream is supported
    if (typeof CompressionStream !== 'undefined') {
      try {
        const cs = new CompressionStream('deflate-raw');
        const writer = cs.writable.getWriter();
        writer.write(rawData);
        writer.close();
        const reader = cs.readable.getReader();
        const chunks = [];
        let total = 0;
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          chunks.push(value);
          total += value.length;
        }
        const merged = new Uint8Array(total);
        let pos = 0;
        for (const ch of chunks) {
          merged.set(ch, pos);
          pos += ch.length;
        }
        if (merged.length < rawData.length) {
          compData = merged;
          method = 8; // DEFLATE
        }
      } catch {
        method = 0;
        compData = rawData;
      }
    }

    const { time, date } = toDosDateTime();

    // Local Header: 30 bytes + pathBytes.length + compData.length
    const lh = new Uint8Array(30 + pathBytes.length + compData.length);
    const lView = new DataView(lh.buffer);
    lView.setUint32(0, 0x04034b50, true);
    lView.setUint16(4, 20, true);
    lView.setUint16(6, 0x0800, true); // UTF-8 filename flag
    lView.setUint16(8, method, true);
    lView.setUint16(10, time, true);
    lView.setUint16(12, date, true);
    lView.setUint32(14, crc, true);
    lView.setUint32(18, compData.length, true);
    lView.setUint32(22, rawData.length, true);
    lView.setUint16(26, pathBytes.length, true);
    lView.setUint16(28, 0, true);
    lh.set(pathBytes, 30);
    lh.set(compData, 30 + pathBytes.length);
    localHeaders.push(lh);

    // Central Directory Header: 46 bytes + pathBytes.length
    const ch = new Uint8Array(46 + pathBytes.length);
    const cView = new DataView(ch.buffer);
    cView.setUint32(0, 0x02014b50, true);
    cView.setUint16(4, 20, true);
    cView.setUint16(6, 20, true);
    cView.setUint16(8, 0x0800, true);
    cView.setUint16(10, method, true);
    cView.setUint16(12, time, true);
    cView.setUint16(14, date, true);
    cView.setUint32(16, crc, true);
    cView.setUint32(20, compData.length, true);
    cView.setUint32(24, rawData.length, true);
    cView.setUint16(28, pathBytes.length, true);
    cView.setUint16(30, 0, true);
    cView.setUint16(32, 0, true);
    cView.setUint16(34, 0, true);
    cView.setUint16(36, 0, true);
    cView.setUint32(38, 0, true);
    cView.setUint32(42, offset, true);
    ch.set(pathBytes, 46);
    centralHeaders.push(ch);

    offset += lh.length;
  }

  const centralDirOffset = offset;
  let centralDirSize = 0;
  for (const ch of centralHeaders) centralDirSize += ch.length;

  const eocd = new Uint8Array(22);
  const eView = new DataView(eocd.buffer);
  eView.setUint32(0, 0x06054b50, true);
  eView.setUint16(4, 0, true);
  eView.setUint16(6, 0, true);
  eView.setUint16(8, entries.length, true);
  eView.setUint16(10, entries.length, true);
  eView.setUint32(12, centralDirSize, true);
  eView.setUint32(16, centralDirOffset, true);
  eView.setUint16(20, 0, true);

  const totalSize = offset + centralDirSize + 22;
  const out = new Uint8Array(totalSize);
  let p = 0;
  for (const lh of localHeaders) {
    out.set(lh, p);
    p += lh.length;
  }
  for (const ch of centralHeaders) {
    out.set(ch, p);
    p += ch.length;
  }
  out.set(eocd, p);
  return out;
}

async function readZipArchive(buffer) {
  const bytes = new Uint8Array(buffer);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  let eocd = -1;
  for (let i = bytes.length - 22; i >= 0; i--) {
    if (view.getUint32(i, true) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd === -1) throw new Error('Not a valid ZIP archive');

  const cdOffset = view.getUint32(eocd + 16, true);
  const totalEntries = view.getUint16(eocd + 10, true);
  const entries = [];
  let p = cdOffset;

  for (let i = 0; i < totalEntries; i++) {
    if (view.getUint32(p, true) !== 0x02014b50) break;
    const method = view.getUint16(p + 10, true);
    const compSize = view.getUint32(p + 20, true);
    const fnLen = view.getUint16(p + 28, true);
    const extraLen = view.getUint16(p + 30, true);
    const commentLen = view.getUint16(p + 32, true);
    const localHeaderOffset = view.getUint32(p + 42, true);

    const fnBytes = bytes.subarray(p + 46, p + 46 + fnLen);
    const filename = new TextDecoder('utf-8').decode(fnBytes);

    const localFnLen = view.getUint16(localHeaderOffset + 26, true);
    const localExtraLen = view.getUint16(localHeaderOffset + 28, true);
    const dataOffset = localHeaderOffset + 30 + localFnLen + localExtraLen;
    const compData = bytes.subarray(dataOffset, dataOffset + compSize);

    let data;
    if (method === 0) {
      data = compData;
    } else if (method === 8) {
      if (typeof DecompressionStream === 'undefined') {
        throw new Error('DecompressionStream not supported in this browser');
      }
      const ds = new DecompressionStream('deflate-raw');
      const writer = ds.writable.getWriter();
      writer.write(compData);
      writer.close();
      const reader = ds.readable.getReader();
      const chunks = [];
      let total = 0;
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        chunks.push(value);
        total += value.length;
      }
      data = new Uint8Array(total);
      let pos = 0;
      for (const ch of chunks) {
        data.set(ch, pos);
        pos += ch.length;
      }
    } else {
      throw new Error(`Unsupported ZIP compression method: ${method}`);
    }

    entries.push({ filename, data });
    p += 46 + fnLen + extraLen + commentLen;
  }
  return entries;
}

function uint8ArrayToBase64(bytes) {
  let binary = '';
  const len = bytes.byteLength;
  const chunkSize = 8192;
  for (let i = 0; i < len; i += chunkSize) {
    const chunk = bytes.subarray(i, Math.min(i + chunkSize, len));
    binary += String.fromCharCode.apply(null, chunk);
  }
  return btoa(binary);
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

// Safely extract all files from a directory entry via webkitGetAsEntry (Safari/Chrome legacy)
function readFileSystemEntry(entry, currentPath = '') {
  const itemPath = currentPath ? `${currentPath}/${entry.name}` : entry.name;
  return new Promise((resolve) => {
    if (entry.isFile) {
      entry.getFile(
        file => resolve([{ path: itemPath, file }]),
        err => {
          console.warn('entry.getFile error:', err);
          resolve([]);
        }
      );
    } else if (entry.isDirectory) {
      const reader = entry.createReader();
      const allEntries = [];

      function readBatch() {
        reader.readEntries(
          async (batch) => {
            if (!batch || batch.length === 0) {
              const childPromises = allEntries.map(child => readFileSystemEntry(child, itemPath));
              const childArrays = await Promise.all(childPromises);
              resolve(childArrays.flat());
            } else {
              allEntries.push(...batch);
              readBatch();
            }
          },
          (err) => {
            console.warn('readEntries error:', err);
            resolve([]);
          }
        );
      }
      readBatch();
    } else {
      resolve([]);
    }
  });
}

// Safely extract all files from a modern FileSystemHandle (Safari 15.2+, Chrome 86+)
async function readFileSystemHandle(handle, currentPath = '') {
  const itemPath = currentPath ? `${currentPath}/${handle.name}` : handle.name;
  const results = [];
  try {
    if (handle.kind === 'file') {
      const file = await handle.getFile();
      results.push({ path: itemPath, file });
    } else if (handle.kind === 'directory') {
      for await (const [name, childHandle] of handle.entries()) {
        const sub = await readFileSystemHandle(childHandle, itemPath);
        results.push(...sub);
      }
    }
  } catch (err) {
    console.warn('readFileSystemHandle error:', err);
  }
  return results;
}

// Comprehensive extraction function supporting Safari, WebKit, and Chromium
async function extractDroppedFiles(dataTransfer) {
  if (!dataTransfer) return [];
  const results = [];
  const items = dataTransfer.items;

  // 1. Try FileSystemHandle API (modern standard)
  if (items && items.length > 0 && typeof items[0].getAsFileSystemHandle === 'function') {
    try {
      const handlePromises = [];
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        if (item.kind === 'file') {
          handlePromises.push(item.getAsFileSystemHandle());
        }
      }
      const handles = (await Promise.all(handlePromises)).filter(Boolean);
      if (handles.length > 0) {
        for (const handle of handles) {
          const files = await readFileSystemHandle(handle);
          results.push(...files);
        }
        if (results.length > 0) return results;
      }
    } catch (e) {
      console.warn('FileSystemHandle fallback:', e);
    }
  }

  // 2. Try webkitGetAsEntry (Safari / WebKit / Chrome folder drop)
  if (items && items.length > 0) {
    try {
      const entries = [];
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        if (item.kind === 'file' && typeof item.webkitGetAsEntry === 'function') {
          const entry = item.webkitGetAsEntry();
          if (entry) entries.push(entry);
        }
      }
      if (entries.length > 0) {
        const entryResults = await Promise.all(entries.map(e => readFileSystemEntry(e)));
        for (const list of entryResults) {
          results.push(...list);
        }
        if (results.length > 0) return results;
      }
    } catch (e) {
      console.warn('webkitGetAsEntry fallback:', e);
    }
  }

  // 3. Fallback: dataTransfer.files
  if (dataTransfer.files && dataTransfer.files.length > 0) {
    for (let i = 0; i < dataTransfer.files.length; i++) {
      const file = dataTransfer.files[i];
      results.push({
        path: file.webkitRelativePath || file.name,
        file: file
      });
    }
  }

  return results;
}

async function compileAndPreviewExtension(fileItems) {
  const statusIndicator = document.getElementById('status-indicator');
  const statusText = document.getElementById('submit-status-text');

  function setStatus(text, type = 'info') {
    if (statusText) statusText.textContent = text;
    if (statusIndicator) {
      statusIndicator.className = 'status-indicator' + (type === 'success' ? ' success' : type === 'error' ? ' error' : '');
    }
  }

  // Check if a single .magicext or .zip package was dropped
  const singlePackage = fileItems.length === 1 && (
    fileItems[0].path.endsWith('.magicext') ||
    fileItems[0].path.endsWith('.zip') ||
    fileItems[0].file?.name.endsWith('.magicext') ||
    fileItems[0].file?.name.endsWith('.zip')
  ) ? fileItems[0] : null;

  let pkgBytes;
  let metadata = {};

  if (singlePackage) {
    setStatus('Reading package archive...');
    try {
      const buf = await singlePackage.file.arrayBuffer();
      const zipEntries = await readZipArchive(buf);
      pkgBytes = new Uint8Array(buf);

      const magicEntry = zipEntries.find(e => e.filename === 'magic.json' || e.filename.endsWith('/magic.json'));
      const manifestEntry = zipEntries.find(e => e.filename === 'manifest.json' || e.filename.endsWith('/manifest.json'));

      let magic = {};
      if (magicEntry) {
        try { magic = JSON.parse(new TextDecoder().decode(magicEntry.data)); } catch {}
      }
      let manifest = {};
      if (manifestEntry) {
        try { manifest = JSON.parse(new TextDecoder().decode(manifestEntry.data)); } catch {}
      }

      metadata.name = magic.name || manifest.name || singlePackage.file.name.replace(/\.(magicext|zip)$/, '');
      metadata.prompt = magic.prompt || manifest.browser_specific_settings?.safari?.prompt || manifest.description || metadata.name;
      metadata.description = magic.description || manifest.description || '';
      metadata.author = magic.author || localStorage.getItem('safari_magic_author') || 'community';
      metadata.selected_symbol = magic.selected_symbol || 'sparkles';
      metadata.symbol_color_name = magic.symbol_color_name || 'blue';
    } catch (err) {
      showToast('Could not read package archive: ' + err.message);
      setStatus('Failed to read package', 'error');
      return;
    }
  } else {
    // Compiling from a dropped folder
    setStatus('Analyzing extension files...');

    // Locate manifest.json
    const manifestItem = fileItems.find(item => {
      const p = item.path.replace(/\\/g, '/');
      return p === 'manifest.json' || p.endsWith('/manifest.json');
    });

    let manifest = null;
    let rootPrefix = '';

    if (manifestItem) {
      const normPath = manifestItem.path.replace(/\\/g, '/');
      const idx = normPath.lastIndexOf('manifest.json');
      rootPrefix = normPath.slice(0, idx);
      try {
        const text = await manifestItem.file.text();
        manifest = JSON.parse(text);
      } catch {
        showToast('manifest.json is not valid JSON.');
        setStatus('Invalid manifest.json', 'error');
        return;
      }
    } else {
      // Synthesize manifest if an HTML file exists
      const htmlItem = fileItems.find(item => item.path.endsWith('.html'));
      if (!htmlItem) {
        showToast('Could not find manifest.json or HTML entry in that folder. Is this a Safari extension?');
        setStatus('Not a valid extension folder', 'error');
        return;
      }
      const folderName = fileItems[0]?.path.split('/')[0] || 'My Extension';
      manifest = {
        manifest_version: 3,
        name: folderName.replace(/[-_]/g, ' '),
        version: '1.0',
        description: `${folderName} Safari Extension`,
        browser_url_overrides: { newtab: 'index.html' },
        browser_specific_settings: {
          safari: { prompt: `Create ${folderName}` }
        },
        icon_variants: [{ any: 'symbol:sparkles' }]
      };
    }

    const name = manifest.name || 'My Extension';
    const description = manifest.description || '';
    const safariPrompt = manifest.browser_specific_settings?.safari?.prompt;
    const prompt = safariPrompt || description || name;

    let symbol = 'puzzlepiece.extension';
    const iconStr = manifest.icon_variants?.[0]?.any || '';
    if (typeof iconStr === 'string' && iconStr.startsWith('symbol:')) {
      symbol = iconStr.replace('symbol:', '');
    } else if (iconStr) {
      symbol = iconStr;
    }

    const savedAuthor = localStorage.getItem('safari_magic_author') || 'community';
    const uuid = (typeof crypto !== 'undefined' && crypto.randomUUID)
      ? crypto.randomUUID().toUpperCase()
      : 'E' + Date.now().toString(16).toUpperCase();

    // Check if magic.json already exists in the folder
    let existingMagic = null;
    const magicItem = fileItems.find(item => {
      const p = item.path.replace(/\\/g, '/');
      return p === rootPrefix + 'magic.json';
    });
    if (magicItem) {
      try {
        existingMagic = JSON.parse(await magicItem.file.text());
      } catch {}
    }

    metadata = {
      name: existingMagic?.name || name,
      author: existingMagic?.author || savedAuthor,
      description: existingMagic?.description || description,
      prompt: existingMagic?.prompt || prompt,
      selected_symbol: existingMagic?.selected_symbol || symbol,
      symbol_color_name: existingMagic?.symbol_color_name || 'blue',
      version: manifest.version || '1.0',
    };

    // Normalize manifest
    if (!manifest.browser_specific_settings) manifest.browser_specific_settings = {};
    if (!manifest.browser_specific_settings.safari) manifest.browser_specific_settings.safari = {};
    manifest.browser_specific_settings.safari.prompt = metadata.prompt;
    manifest.icon_variants = [{ any: `symbol:${metadata.selected_symbol}` }];

    // Construct magic.json
    const magicData = {
      magic_format_version: 1,
      id: existingMagic?.id || uuid,
      name: metadata.name,
      author: metadata.author,
      version: metadata.version,
      description: metadata.description,
      prompt: metadata.prompt,
      selected_symbol: metadata.selected_symbol,
      symbol_color_name: metadata.symbol_color_name,
      packaged_at: new Date().toISOString()
    };

    setStatus('Compiling files into .magicext bundle...');

    // Collect zip entries
    const zipEntries = [];
    zipEntries.push({
      path: 'magic.json',
      data: new TextEncoder().encode(JSON.stringify(magicData, null, 2))
    });
    zipEntries.push({
      path: 'manifest.json',
      data: new TextEncoder().encode(JSON.stringify(manifest, null, 2))
    });

    for (const item of fileItems) {
      const normPath = item.path.replace(/\\/g, '/');
      if (!normPath.startsWith(rootPrefix)) continue;
      const relPath = normPath.slice(rootPrefix.length);
      if (!relPath || relPath === 'magic.json' || relPath === 'manifest.json') continue;

      const parts = relPath.split('/');
      const isIgnored = parts.some(part => IGNORE_PATTERNS.some(regex => regex.test(part)));
      if (isIgnored) continue;

      const fileBuf = await item.file.arrayBuffer();
      zipEntries.push({
        path: relPath,
        data: new Uint8Array(fileBuf)
      });
    }

    try {
      pkgBytes = await createZipArchive(zipEntries);
    } catch (err) {
      showToast('Error packaging .magicext: ' + err.message);
      setStatus('Packaging failed', 'error');
      return;
    }
  }

  await handlePackageReady(pkgBytes, metadata);
}

async function handlePackageReady(pkgBytes, metadata) {
  const preview = document.getElementById('submit-preview');
  const dropzone = document.getElementById('submit-dropzone');
  const statusIndicator = document.getElementById('status-indicator');
  const statusText = document.getElementById('submit-status-text');
  const authorInput = document.getElementById('submit-author-input');
  const downloadBtn = document.getElementById('submit-download-btn');
  const ghBtn = document.getElementById('submit-github-btn');

  function setStatus(text, type = 'info') {
    if (statusText) statusText.textContent = text;
    if (statusIndicator) {
      statusIndicator.className = 'status-indicator' + (type === 'success' ? ' success' : type === 'error' ? ' error' : '');
    }
  }

  const safeName = (metadata.name || 'Extension').replace(/[^a-zA-Z0-9_-]/g, '_').replace(/^_+|_+$/g, '') || 'Extension';
  const filename = `${safeName}.magicext`;
  const slug = (metadata.name || 'extension').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'extension';

  // Display metadata
  document.getElementById('preview-name').textContent = metadata.name;
  document.getElementById('preview-prompt').textContent = metadata.prompt ? `"${metadata.prompt}"` : '';
  document.getElementById('preview-icon').textContent = metadata.selected_symbol ? '🪄' : '📦';
  document.getElementById('preview-filename').textContent = filename;
  document.getElementById('preview-filesize').textContent = `(${formatBytes(pkgBytes.length)})`;

  // Set author handle
  if (authorInput) {
    const savedAuthor = localStorage.getItem('safari_magic_author') || metadata.author || '';
    authorInput.value = savedAuthor;
  }

  // Setup download button
  const blob = new Blob([pkgBytes], { type: 'application/zip' });
  if (downloadBtn) {
    downloadBtn.onclick = () => {
      downloadBlob(blob, filename);
      showToast(`Downloaded ${filename}!`);
    };
  }

  // Base64 encoding
  const b64Payload = uint8ArrayToBase64(pkgBytes);

  let uploadedUrl = null;

  function updateGhLink() {
    const author = (authorInput?.value || '').trim() || metadata.author || 'community';
    let pkgField = '';
    if (uploadedUrl) {
      pkgField += `Download link: ${uploadedUrl}\n\n`;
    }
    if (b64Payload.length < 2500) {
      pkgField += `<!-- MAGICEXT_BASE64_START -->\n${b64Payload}\n<!-- MAGICEXT_BASE64_END -->`;
    }
    if (!uploadedUrl && b64Payload.length >= 2500) {
      pkgField += `*Package compiled locally (${filename}). Please attach the downloaded file below.*`;
    }

    const params = new URLSearchParams({
      template: 'extension_submission.yml',
      title: `[Extension Submission]: ${metadata.name}`,
      extension_name: metadata.name,
      author_handle: author,
      ai_prompt: metadata.prompt || metadata.name,
      description: metadata.description || '',
      selected_symbol: metadata.selected_symbol || 'puzzlepiece.extension',
      symbol_color: metadata.symbol_color_name || 'blue',
      package_upload: pkgField,
    });
    ghBtn.href = `https://github.com/${GITHUB_REPO}/issues/new?${params.toString()}`;
  }

  updateGhLink();

  if (authorInput) {
    authorInput.oninput = () => {
      localStorage.setItem('safari_magic_author', authorInput.value.trim());
      updateGhLink();
    };
  }

  preview.classList.remove('hidden');
  dropzone.classList.add('dropzone-done');
  showToast(`Compiled "${filename}" (${formatBytes(pkgBytes.length)})!`);

  // Concurrently upload to tmpfiles.org as automated ingest link
  setStatus('Uploading package to secure temporary link...', 'info');
  try {
    const formData = new FormData();
    formData.append('file', blob, `${slug}.zip`);
    const resp = await fetch('https://tmpfiles.org/api/v1/upload', {
      method: 'POST',
      body: formData
    });
    if (resp.ok) {
      const resJson = await resp.json();
      if (resJson?.data?.url) {
        uploadedUrl = resJson.data.url;
        updateGhLink();
        setStatus('✓ .magicext compiled & pre-attached! Ready to submit.', 'success');
        return;
      }
    }
  } catch (err) {
    console.warn('tmpfiles upload notice:', err);
  }

  if (b64Payload.length < 2500) {
    setStatus('✓ .magicext compiled & embedded! Ready to submit.', 'success');
  } else {
    setStatus('✓ .magicext compiled! Download and attach to GitHub.', 'success');
  }
}

function setupDropzone() {
  const dropzone = document.getElementById('submit-dropzone');
  const folderInput = document.getElementById('submit-folder-input');
  const preview = document.getElementById('submit-preview');
  if (!dropzone || !folderInput || !preview) return;

  function handleDragOver(e) {
    e.preventDefault();
    e.stopPropagation();
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = 'copy';
    }
    dropzone.classList.add('dropzone-over');
  }

  function handleDragLeave(e) {
    e.preventDefault();
    e.stopPropagation();
    dropzone.classList.remove('dropzone-over');
  }

  dropzone.addEventListener('dragenter', handleDragOver);
  dropzone.addEventListener('dragover', handleDragOver);
  dropzone.addEventListener('dragleave', handleDragLeave);
  dropzone.addEventListener('dragend', handleDragLeave);

  dropzone.addEventListener('drop', async (e) => {
    e.preventDefault();
    e.stopPropagation();
    dropzone.classList.remove('dropzone-over');

    try {
      showToast('Processing dropped files...');
      const allFiles = await extractDroppedFiles(e.dataTransfer);
      if (allFiles && allFiles.length > 0) {
        await compileAndPreviewExtension(allFiles);
      } else {
        showToast('Could not read files from dropped item. Please use "browse folder".');
      }
    } catch (err) {
      console.error('Drop error:', err);
      showToast('Error reading dropped folder: ' + err.message);
    }
  });

  // Prevent Safari default file navigation when dropping outside dropzone
  window.addEventListener('dragover', (e) => {
    e.preventDefault();
  });
  window.addEventListener('drop', (e) => {
    e.preventDefault();
  });

  dropzone.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') folderInput.click();
  });

  folderInput.addEventListener('change', async () => {
    if (folderInput.files.length) {
      const allFiles = Array.from(folderInput.files).map(f => ({
        path: f.webkitRelativePath || f.name,
        file: f
      }));
      await compileAndPreviewExtension(allFiles);
    }
  });
}

document.addEventListener('DOMContentLoaded', initGallery);


