/**
 * Safari Magic Gallery — gallery logic.
 *
 * Data comes from community_registry.json, generated by scripts/build_registry.py.
 * Every extension is presented equally in one grid; users choose the order with
 * the sort control. Thumbnails are real screenshots (see generate_thumbnails.sh).
 */

// ---------------------------------------------------------------- state
let extensions = [];
let activeCategory = 'all';
let searchQuery = '';
let sortMode = 'newest';

let lastFocusedElement = null;

// ---------------------------------------------------------------- elements
const grid = document.getElementById('extension-grid');
const ribbonButtons = document.querySelectorAll('.ribbon-icon-btn');
const toastEl = document.getElementById('toast');
const searchInput = document.getElementById('search-input');
const searchClear = document.getElementById('search-clear');
const sortSelect = document.getElementById('sort-select');
const resultCount = document.getElementById('result-count');

const inspectorModal = document.getElementById('inspector-modal');
const closeInspectorBtn = document.getElementById('close-inspector-btn');
const modalTitle = document.getElementById('modal-title');
const modalAuthor = document.getElementById('modal-author');
const modalCategory = document.getElementById('modal-category');
const modalImg = document.getElementById('modal-img');
const modalDescription = document.getElementById('modal-description');
const modalPrompt = document.getElementById('modal-prompt');
const modalCliCmd = document.getElementById('modal-cli-cmd');
const modalDownloadPkgBtn = document.getElementById('modal-download-pkg-btn');
const modalDownloadLabel = document.getElementById('modal-download-label');
const modalMetaRow = document.getElementById('modal-meta-row');
const modalSetupLink = document.getElementById('modal-setup-link');
const copyModalPromptBtn = document.getElementById('copy-modal-prompt-btn');
const copyModalCliBtn = document.getElementById('copy-modal-cli-btn');

const submitModal = document.getElementById('submit-modal');
const openSubmitModalBtn = document.getElementById('open-submit-modal-btn');
const heroBecomeAuthorBtn = document.getElementById('hero-become-author-btn');
const footerSubmitBtn = document.getElementById('footer-submit-btn');
const closeSubmitBtn = document.getElementById('close-submit-btn');

const PLACEHOLDER_ART = 'assets/hero_cyberpunk.jpg';

// ---------------------------------------------------------------- boot
async function initGallery() {
  setupEventListeners();

  try {
    const res = await fetch('community_registry.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error(`registry responded ${res.status}`);
    const data = await res.json();
    extensions = Array.isArray(data.extensions) ? data.extensions : [];
  } catch (err) {
    renderLoadError(err);
    return;
  }

  if (extensions.length === 0) {
    renderEmptyState();
    return;
  }

  render();
  openFromHash();
  window.addEventListener('hashchange', openFromHash);
}

// ---------------------------------------------------------------- helpers
function categoriesFor(ext) {
  const values = Array.isArray(ext.tags) ? [...ext.tags] : [];
  if (ext.category) values.push(ext.category);
  return values.map(v => String(v).toLowerCase());
}

function safeUrl(url) {
  if (!url) return '';
  const value = String(url);
  if (/^(https?:)?\/\//i.test(value) || value.startsWith('/')) return value;
  if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return ''; // reject javascript:, data:, etc.
  return value;
}

function artFor(ext) {
  return safeUrl(ext.art_image) || PLACEHOLDER_ART;
}

function installCommandFor(ext) {
  return `safari-magic-ext install ${ext.id}`;
}

function matchesSearch(ext, query) {
  if (!query) return true;
  const haystack = [
    ext.name, ext.description, ext.prompt, ext.author, ext.id, ext.category,
    ...(Array.isArray(ext.tags) ? ext.tags : []),
  ].filter(Boolean).join(' ').toLowerCase();
  return query.toLowerCase().split(/\s+/).filter(Boolean).every(t => haystack.includes(t));
}

function sortExtensions(list) {
  const copy = [...list];
  switch (sortMode) {
    case 'oldest':
      return copy.sort((a, b) => (a.added_at || '').localeCompare(b.added_at || ''));
    case 'name':
      return copy.sort((a, b) => (a.name || '').localeCompare(b.name || ''));
    case 'author':
      return copy.sort((a, b) =>
        (a.author || '').localeCompare(b.author || '') ||
        (a.name || '').localeCompare(b.name || ''));
    case 'newest':
    default:
      // Most recent first; ties fall back to name for a stable order.
      return copy.sort((a, b) =>
        (b.added_at || '').localeCompare(a.added_at || '') ||
        (a.name || '').localeCompare(b.name || ''));
  }
}

function visibleExtensions() {
  const filtered = extensions.filter(
    ext =>
      (activeCategory === 'all' || categoriesFor(ext).includes(activeCategory)) &&
      matchesSearch(ext, searchQuery)
  );
  return sortExtensions(filtered);
}

// ---------------------------------------------------------------- render
function render() {
  const list = visibleExtensions();
  renderCount(list.length);
  renderGrid(list);
}

function renderCount(shown) {
  if (!resultCount) return;
  const total = extensions.length;
  resultCount.textContent =
    shown === total
      ? `${total} extension${total === 1 ? '' : 's'}`
      : `${shown} of ${total} shown`;
}

function renderGrid(list) {
  if (list.length === 0) {
    grid.innerHTML = `
      <p class="grid-empty-note">
        Nothing matches that.
        <button type="button" class="link-inline" id="reset-filters">Clear filters</button>
      </p>`;
    const reset = document.getElementById('reset-filters');
    if (reset) reset.addEventListener('click', resetFilters);
    return;
  }

  grid.innerHTML = list.map(ext => `
    <article class="ext-card" data-id="${escapeHTML(ext.id)}" role="button" tabindex="0"
             aria-label="${escapeHTML(ext.name)} by ${escapeHTML(ext.author || 'community')} — view install instructions">
      <div class="ext-card-media">
        <img src="${escapeHTML(artFor(ext))}" alt="Preview of ${escapeHTML(ext.name)}" loading="lazy">
      </div>
      <div class="ext-card-body">
        <h3 class="ext-card-title">${escapeHTML(ext.name)}</h3>
        <p class="ext-card-author">by @${escapeHTML(ext.author || 'community')}</p>
        <p class="ext-card-desc">${escapeHTML(ext.description || '')}</p>
        <div class="ext-card-tags">
          ${(ext.tags || []).map(t => `<span class="ext-tag">#${escapeHTML(t)}</span>`).join('')}
        </div>
      </div>
      <div class="ext-card-foot">
        <span class="ext-card-cta">Install →</span>
      </div>
    </article>`).join('');

  grid.querySelectorAll('.ext-card').forEach(card => {
    const open = () => {
      const item = extensions.find(e => e.id === card.getAttribute('data-id'));
      if (item) openInspector(item);
    };
    card.addEventListener('click', open);
    card.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    });
  });
}

function renderLoadError(err) {
  console.error('Could not load community_registry.json:', err);
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML = `
    <p class="grid-empty-note">
      Could not load the extension catalog.<br>
      If you opened this file directly, serve it over HTTP instead:
      <code>python3 -m http.server 8000 --directory web</code>
    </p>`;
}

function renderEmptyState() {
  if (resultCount) resultCount.textContent = '';
  grid.innerHTML =
    '<p class="grid-empty-note">No extensions published yet. Be the first to share one.</p>';
}

function resetFilters() {
  activeCategory = 'all';
  searchQuery = '';
  if (searchInput) searchInput.value = '';
  if (searchClear) searchClear.classList.add('hidden');
  ribbonButtons.forEach(b => {
    const isAll = b.getAttribute('data-filter') === 'all';
    b.classList.toggle('active', isAll);
    b.setAttribute('aria-pressed', String(isAll));
  });
  render();
}

// ---------------------------------------------------------------- inspector
function openInspector(ext, { updateHash = true } = {}) {
  modalTitle.textContent = ext.name;
  modalAuthor.textContent = `by @${ext.author || 'community'}`;
  modalCategory.textContent = (ext.category || 'extension').toUpperCase();
  modalImg.src = artFor(ext);
  modalImg.alt = `Preview of ${ext.name}`;
  modalDescription.textContent = ext.description || 'Safari AI Magic Extension';
  modalPrompt.textContent = ext.prompt ? `"${ext.prompt}"` : 'No prompt was recorded for this one.';

  const cliCommand = installCommandFor(ext);
  modalCliCmd.textContent = cliCommand;

  const download = safeUrl(ext.download_url);
  const filename = download.split('/').pop() || `${ext.name}.magicext`;
  modalDownloadPkgBtn.href = download;
  modalDownloadPkgBtn.download = filename;
  if (modalDownloadLabel) modalDownloadLabel.textContent = `Download ${filename}`;

  const bits = [`id: ${ext.id}`];
  if (ext.version) bits.push(`v${ext.version}`);
  if (Array.isArray(ext.tags) && ext.tags.length) bits.push(ext.tags.map(t => `#${t}`).join(' '));
  modalMetaRow.textContent = bits.join('  ·  ');

  copyModalPromptBtn.onclick = () =>
    copyText(ext.prompt, 'Prompt copied. Paste it into Safari to remix.');
  copyModalCliBtn.onclick = () => copyText(cliCommand, 'Install command copied.');

  if (updateHash) history.replaceState(null, '', `#ext=${encodeURIComponent(ext.id)}`);
  openModal(inspectorModal);
}

function openFromHash() {
  const hash = window.location.hash;
  if (hash === '#submit') {
    if (submitModal.classList.contains('hidden')) openModal(submitModal);
    return;
  }
  const match = /^#ext=(.+)$/.exec(hash);
  if (!match) return;
  const id = decodeURIComponent(match[1]);
  const ext = extensions.find(e => e.id === id);
  if (ext && inspectorModal.classList.contains('hidden')) {
    openInspector(ext, { updateHash: false });
  }
}

// ---------------------------------------------------------------- modals
function openModal(modal) {
  lastFocusedElement = document.activeElement;
  modal.classList.remove('hidden');
  modal.removeAttribute('aria-hidden');
  document.body.classList.add('modal-open');
  const focusTarget = modal.querySelector('.modal-pixel-close');
  if (focusTarget) focusTarget.focus();
}

function closeModal(modal) {
  modal.classList.add('hidden');
  modal.setAttribute('aria-hidden', 'true');
  document.body.classList.remove('modal-open');
  if (modal === inspectorModal && window.location.hash.startsWith('#ext=')) {
    history.replaceState(null, '', window.location.pathname + window.location.search);
  }
  if (lastFocusedElement && typeof lastFocusedElement.focus === 'function') {
    lastFocusedElement.focus();
    lastFocusedElement = null;
  }
}

function trapFocus(e, modal) {
  if (e.key !== 'Tab') return;
  const focusables = [
    ...modal.querySelectorAll(
      'a[href], button:not([disabled]), input, textarea, select, summary, [tabindex]:not([tabindex="-1"])'
    ),
  ].filter(el => el.offsetParent !== null);
  if (focusables.length === 0) return;
  const first = focusables[0];
  const last = focusables[focusables.length - 1];
  if (e.shiftKey && document.activeElement === first) {
    e.preventDefault();
    last.focus();
  } else if (!e.shiftKey && document.activeElement === last) {
    e.preventDefault();
    first.focus();
  }
}

// ---------------------------------------------------------------- events
function setupEventListeners() {
  ribbonButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      ribbonButtons.forEach(b => {
        b.classList.remove('active');
        b.setAttribute('aria-pressed', 'false');
      });
      btn.classList.add('active');
      btn.setAttribute('aria-pressed', 'true');
      activeCategory = (btn.getAttribute('data-filter') || 'all').toLowerCase();
      render();
    });
  });

  if (sortSelect) {
    sortSelect.addEventListener('change', () => {
      sortMode = sortSelect.value;
      render();
    });
  }

  if (searchInput) {
    searchInput.addEventListener('input', () => {
      searchQuery = searchInput.value.trim();
      searchClear.classList.toggle('hidden', searchQuery === '');
      render();
    });
    searchInput.addEventListener('keydown', e => {
      if (e.key === 'Escape' && searchInput.value) {
        e.stopPropagation();
        searchInput.value = '';
        searchQuery = '';
        searchClear.classList.add('hidden');
        render();
      }
    });
  }
  if (searchClear) {
    searchClear.addEventListener('click', () => {
      searchInput.value = '';
      searchQuery = '';
      searchClear.classList.add('hidden');
      searchInput.focus();
      render();
    });
  }

  closeInspectorBtn.addEventListener('click', () => closeModal(inspectorModal));
  inspectorModal.addEventListener('click', e => {
    if (e.target === inspectorModal) closeModal(inspectorModal);
  });
  inspectorModal.addEventListener('keydown', e => trapFocus(e, inspectorModal));
  if (modalSetupLink) modalSetupLink.addEventListener('click', () => closeModal(inspectorModal));

  const openSubmit = () => openModal(submitModal);
  [openSubmitModalBtn, heroBecomeAuthorBtn, footerSubmitBtn].forEach(btn => {
    if (btn) btn.addEventListener('click', openSubmit);
  });
  if (closeSubmitBtn) closeSubmitBtn.addEventListener('click', () => closeModal(submitModal));
  submitModal.addEventListener('click', e => {
    if (e.target === submitModal) closeModal(submitModal);
  });
  submitModal.addEventListener('keydown', e => trapFocus(e, submitModal));

  document.addEventListener('keydown', e => {
    if (e.key !== 'Escape') return;
    if (!inspectorModal.classList.contains('hidden')) closeModal(inspectorModal);
    if (!submitModal.classList.contains('hidden')) closeModal(submitModal);
  });
}

// ---------------------------------------------------------------- utilities
function copyText(text, successMsg) {
  if (!text) return;
  const fallback = () => {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.position = 'absolute';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    try {
      document.execCommand('copy');
      showToast(successMsg || 'Copied to clipboard.');
    } catch {
      showToast('Could not copy. Select the text and copy manually.');
    }
    document.body.removeChild(ta);
  };
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text)
      .then(() => showToast(successMsg || 'Copied to clipboard.'))
      .catch(fallback);
  } else {
    fallback();
  }
}

let toastTimer = null;
function showToast(msg) {
  toastEl.textContent = msg;
  toastEl.classList.remove('hidden');
  if (toastTimer) clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toastEl.classList.add('hidden'), 2600);
}

function escapeHTML(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

document.addEventListener('DOMContentLoaded', initGallery);
